# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Config-YAML
version:      0.1
version_from: YAML.pm
installdirs:  site
requires:
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
